site_name: Grind Mode Activated
site_url: https://grindmodeactivated.github.io

theme:
  name: windmill
  highlightjs: true  # ✅ Enables code highlighting
  # Windmill doesn't support palette, font, or features like Material does

extra_css:
  - assets/stylesheets/extra.css  # ✅ Keep this if you have custom CSS

nav:
  - Home: index.md
  - Crypto :
      - Posts :
        - "Looking for alpha on Polymarket" : Crypto/poly_ct.md
        - "Looking for alpha on HyperLiquid vaults" : Crypto/HPLvaults.md
  - FPL:
      - Overview: FPL/index.md
      - Posts:
          - "GW6 - HoF review": FPL/GW6 - HoF review.md
          - "GW6 - early thoughts": FPL/GW6_early_thoughts.md
          - "GW6 - content creator review": FPL/GW6_ccr.md
          - "GW8 - HoF review": FPL/GW8 - HoF review.md
          - "GW8 - early thoughts": FPL/GW8_early_thoughts.md
          - "GW9 - HoF review": FPL/GW9_hof.md
          - "GW9 - Early thoughts": FPL/GW9_et.md
          - "GW9 - Chip strategy": FPL/GW9_cs.md
          - "GW11 - HoF review": FPL/GW11_hof.md
          - "GW11 - Early thoughts": FPL/GW11_et.md
          - "GW12 - HoF review": FPL/GW12_hof.md
  - Movie Reviews:
      - Overview: Movie reviews/index.md
      - Posts:
          - "Naked Gun": Movie reviews/NakedGun.md
          - "Swiped": Movie reviews/Swiped.md
  - Miscellaneous:
    - Posts:
        - "Pushups in 60s": Miscellaneous/60spushups.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.arithmatex: { generic: true }
  - tables
  - toc:
      permalink: true

plugins:
  - search